package ooga.event;

public enum GameEventType {
  VIEW_TO_CONTROLLER_GAME_START,
  VIEW_TO_CONTROLLER_ROLL_DICE,
  CONTROLLER_TO_VIEW_INIT_DATA,
  CONTROLLER_TO_VIEW_UPDATE_DATA,
  CONTROLLER_TO_MODEL_ROLL_DICE,
  MODEL_TO_CONTROLLER_DICE_ROLLED
}
